/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'deviceId', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviceId: number | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DeviceSchema extends BaseModel {
  static $columns = ['approvedAt', 'approvedBy', 'createdAt', 'id', 'ip', 'label', 'lastSeenAt', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = DeviceSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column()
  declare approvedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ip: string | null
  @column()
  declare label: string | null
  @column.dateTime()
  declare lastSeenAt: DateTime | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: number | null
}

export class RoomInviteSchema extends BaseModel {
  static $columns = ['createdAt', 'fromUserId', 'id', 'roomId', 'status', 'toUserId', 'updatedAt'] as const
  $columns = RoomInviteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromUserId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roomId: number
  @column()
  declare status: string
  @column()
  declare toUserId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoomSignalSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'fromPeer', 'id', 'roomCode', 'toPeer', 'type'] as const
  $columns = RoomSignalSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: string
  @column()
  declare fromPeer: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare roomCode: string
  @column()
  declare toPeer: string
  @column()
  declare type: string
}

export class RoomSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'expiresAt', 'hostName', 'hostPeerId', 'id', 'players', 'updatedAt', 'userId', 'worldKind'] as const
  $columns = RoomSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hostName: string
  @column()
  declare hostPeerId: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare players: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare worldKind: string
}

export class SaveSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'kind', 'night', 'payload', 'players', 'seconds', 'size', 'updatedAt', 'userId'] as const
  $columns = SaveSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare night: number
  @column()
  declare payload: string
  @column()
  declare players: number
  @column()
  declare seconds: number
  @column()
  declare size: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class ScoreSchema extends BaseModel {
  static $columns = ['createdAt', 'deaths', 'id', 'kills', 'nights', 'score', 'seconds', 'updatedAt', 'userId'] as const
  $columns = ScoreSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deaths: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kills: number
  @column()
  declare nights: number
  @column()
  declare score: number
  @column()
  declare seconds: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'key', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'isAdmin', 'isDisabled', 'lastLoginAt', 'name', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isAdmin: boolean
  @column()
  declare isDisabled: boolean
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
