import { defineConfig } from '@adonisjs/vite'

const viteBackendConfig = defineConfig({
  /**
   * The output of vite will be written inside this directory. The path should be
   * relative from the application root. public/assets is taken by the game's models.
   */
  buildDirectory: 'public/build',

  /**
   * The path to the manifest file generated by the "vite build" command.
   */
  manifestFile: 'public/build/.vite/manifest.json',

  /**
   * Public path of the build directory, prefixed to every URL of a compiled asset.
   */
  assetsUrl: '/build',

  scriptAttributes: {
    defer: true,
  },
})

export default viteBackendConfig
